# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 400)
        MainWindow.setMinimumSize(QtCore.QSize(730, 400))
        MainWindow.setMaximumSize(QtCore.QSize(730, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/JLUgeo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.pyqtgraph = PlotWidget(self.centralwidget)
        self.pyqtgraph.setGeometry(QtCore.QRect(20, 20, 375, 320))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        self.pyqtgraph.setFont(font)
        self.pyqtgraph.setObjectName("pyqtgraph")
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(410, 50, 301, 221))
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeView.setAutoScroll(False)
        self.treeView.setObjectName("treeView")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(660, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.browseButton.setFont(font)
        self.browseButton.setObjectName("browseButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(410, 20, 241, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.lineEdit.setFont(font)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(567, 300, 144, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(410, 290, 145, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(410, 320, 145, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 730, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        self.menuSetting.setObjectName("menuSetting")
        MainWindow.setMenuBar(self.menuBar)
        self.About = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.About.setFont(font)
        self.About.setObjectName("About")
        self.menuSetting.addAction(self.About)
        self.menuBar.addAction(self.menuSetting.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.browseButton, self.treeView)
        MainWindow.setTabOrder(self.treeView, self.lineEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rock Spectrum Assistant"))
        self.pyqtgraph.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>根据选择数据绘出的结果图</p></body></html>"))
        self.browseButton.setText(_translate("MainWindow", "browse"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.checkBox_2.setText(_translate("MainWindow", "Always on top"))
        self.checkBox.setText(_translate("MainWindow", "Autosave"))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting"))
        self.About.setText(_translate("MainWindow", "About"))

from pyqtgraph import PlotWidget
import apprcc_rc
